version: '3.7'

services:
  db:
    build: 
      context: .
      dockerfile: .dockerfile
    image: github.com/kevindotklein/guava-db
    container_name: guava-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: guava
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/guava-db
    volumes:
      - guava-db:/var/lib/postgresql/data

volumes:
  guava-db: