server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/guava-api}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  
  jpa:
    open-in-view: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  public-key: classpath:public_key.pem
  private-key: classpath:private_key.pem